"""Reset DB with new schema and in batch mode so it can be updated.

Revision ID: 78093120e7db
Revises: 
Create Date: 2022-04-20 00:40:26.182830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78093120e7db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('spotify_access_token', sa.String(length=255), nullable=True),
    sa.Column('spotify_access_expires', sa.DateTime(), nullable=True),
    sa.Column('spotify_refresh_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_host_username'), ['username'], unique=True)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('artist', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.drop_table('event')
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_host_username'))

    op.drop_table('host')
    # ### end Alembic commands ###
