"""Adds spotify id values to event and song.

Revision ID: 87bf94cb0fd8
Revises: a4d1f702f0dd
Create Date: 2022-04-07 21:57:52.326872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bf94cb0fd8'
down_revision = 'a4d1f702f0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('spotify_id', sa.String(length=64), nullable=True))
    op.add_column('song', sa.Column('spotify_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'spotify_id')
    op.drop_column('event', 'spotify_id')
    # ### end Alembic commands ###
